# flask-service-monitored.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: default
  labels:
    app: flask-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  selector:
    app: flask-api
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
