# pagerduty-webhook.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagerduty-webhook
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagerduty-webhook
  template:
    metadata:
      labels:
        app: pagerduty-webhook
    spec:
      containers:
      - name: webhook
        image: curlimages/curl:8.5.0
        command:
        - sh
        - -c
        - |
          while true; do
            curl -s -X POST \
              "https://events.pagerduty.com/v2/enqueue" \
              -H "Content-type: application/json" \
              -d '{
                "routing_key": "YOUR_INTEGRATION_KEY_HERE",
                "event_action": "trigger",
                "payload": {
                  "summary": "K8s Alert: {{ .GroupLabels.alertname }}",
                  "severity": "{{ if eq .Status \"firing\" }}critical{{ else }}info{{ end }}",
                  "source": "prometheus.monitoring.svc",
                  "custom_details": {
                    "namespace": "{{ .GroupLabels.namespace }}",
                    "pod": "{{ .GroupLabels.pod }}",
                    "sli": "{{ .GroupLabels.sli }}"
                  }
                }
              }'
            sleep 30
          done
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-pagerduty
  namespace: monitoring
data:
  config.yml: |
    global:
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
    
    templates:
    - '/etc/alertmanager/template.tmpl'
    
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'pagerduty'
    
    receivers:
    - name: 'pagerduty'
      webhook_configs:
      - url: 'http://pagerduty-webhook.monitoring.svc:8080/notify'
        send_resolved: true
    
    inhibit_rules:
    - source_match:
      - severity = 'none'
      target_match:
      - alertname = 'Watchdog'
